### ISSUE TITLE
crema does not compile with latest llvm (3.6.2)

### ISSUE THREAD

**Issue by hannob** [ainfosec/crema#1]
Compiling crema on my system leads to this error:
g++  -c `llvm-config --cxxflags` -Wno-cast-qual -std=c++11 -g parser.cpp
In file included from ast.h:20:0,
                 from parser.y:3:
codegen.h:27:43: fatal error: llvm/Assembly/PrintModulePass.h: No such file or directory

The file llvm/Assembly/PrintModulePass.h is not part of the current version of llvm. It was part in some older versions.

**Comment by gingerhendrix** [comment]
Downgrading llvm to 3.4.2 worked for me
